version: "3"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user'
      POSTGRES_DB: 'tabela'
    networks:
      - datanett
  restaurant:
    depends_on:
      - db
    build:
      context: ./res
      dockerfile: Dockerfile-res
    networks:
      - datanett
    tmpfs:
      - /run
      - /var/cache
    command: ["python3", "app.py"]
  police:
    depends_on:
    - db
    build:
      context: ./pol
      dockerfile: Dockerfile-pol
    networks:
      - datanett
    tmpfs:
      - /run
      - /var/cache
    command: ["python3", "app.py"]
  web:
    depends_on:
    - db
    build:
      context: ./web
      dockerfile: Dockerfile-web
    networks:
      - datanett
    command: ["adev", "runserver"]

networks:
  datanett: