FROM ubuntu

RUN apt-get update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

RUN pip3 install pandas
RUN pip3 install aiohttp-devtools

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN adev start . --template-engine jinja --session secure --database pg-sqlalchemy --example none
RUN pip3 install -r requirements.txt

ENV AIO_APP_PATH="app/"
ENV AIO_STATIC_PATH="static/"

EXPOSE 5000
EXPOSE 5001
