FROM python:3.7

RUN pip3 install aiohttp-devtools

RUN adev start . --template-engine jinja --session secure --database pg-sqlalchemy --example none
RUN pip3 install -r requirements.txt

ENV AIO_APP_PATH="app/"
ENV AIO_STATIC_PATH="static/"

